services:
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:8.5.2
    container_name: nzbhydra
    hostname: nzbhydra
    restart: unless-stopped
    ports:
      - 5076:5076
    networks:
      - proxy-network
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${DOCKER_DATA}/services/nzbhydra/data:/config
      - /mnt/nas/download:/downloads    

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.5.5
    container_name: sabnzbd
    hostname: sabnzbd
    restart: unless-stopped
    ports:
      - 8060:8080
    networks:
      - proxy-network
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${DOCKER_DATA}/services/sabnzbd/config:/config
      - /mnt/nas/download:/downloads
      - /mnt/nas/download/incomplete:/incomplete-downloads

networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true