# --------------------------------------------------------------------------------
# EXTENSION FIELDS & ANCHORS (Templates)
# --------------------------------------------------------------------------------

# 1. Environment Variables Template
x-env-common: &env-common
  TZ: ${TZ}
  PUID: ${PUID}
  PGID: ${PGID}
  VERSION: ${VERSION:-public}
  PLEX_CLAIM: ${PLEX_CLAIM}

# 2. Base Service Template (Image, Restart, Security, GPU)
x-plex-base: &plex-base
  image: ghcr.io/linuxserver/plex:1.43.1
  restart: unless-stopped
  security_opt:
    - no-new-privileges:true
  env_file:
    - .env
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu, compute, video, utility]

# --------------------------------------------------------------------------------
# SERVICES
# --------------------------------------------------------------------------------
services:
  # --- PRODUCTION PLEX (Default) ---
  plex:
    <<: *plex-base
    container_name: plex
    hostname: plex
    network_mode: "host"
    environment:
      <<: *env-common
    volumes:
      - ${DOCKER_DATA}/plex:/config
      - /mnt/media:/mnt/media
      - /mnt/nas:/mnt/private
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 2G
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:32400/web || exit 1

  # --- TEST PLEX (Only starts with --profile test) ---
  plex-test:
    <<: *plex-base
    container_name: plex-test
    hostname: plex-test
    profiles: ["test"]
    networks:
      - proxy-network
    
    # Specific Environment overrides for Test
    environment:
      <<: *env-common
      VERSION: public                                  # Override
      ADVERTISE_IP: 'http://192.168.10.90:32500/'      # Add
      ALLOWED_NETWORKS: '192.168.10.0/24,17.22.0.0/16' # Add
    volumes:
      - ${DOCKER_DATA}/plex-test:/config  # Specific Config
      - /mnt/media:/mnt/media:ro             # Shared
      - type: tmpfs                          # Shared
        target: /tmp
        tmpfs:
          size: 2G
    ports:
      - "32500:32400"        # Plex Web UI (Mapped to 32500)
      - "32469:32469"        # DLNA
      - "1900:1900/udp"      # DLNA discovery
      - "3005:3005"          # GDM network discovery
      - "5353:5353/udp"      # Bonjour/Avahi
      - "8324:8324"          # Plex Companion
      - "32410:32410/udp"    # GDM
      - "32412:32412/udp"    # GDM
      - "32413:32413/udp"    # GDM
      - "32414:32414/udp"    # GDM

networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true
