services:
  nzbdav:
    image: ghcr.io/nzbdav-dev/nzbdav@sha256:a0a1a01c1af17f0a50949cb8274ee7d40e366e183d1be20f769edb825bdc598f #ghcr.io/nzbdav-dev/nzbdav:0.6.1
    container_name: nzbdav
    hostname: nzbdav
    restart: unless-stopped
    ports:
      - 3003:3000
    networks:
      - proxy-network
    env_file:
      - ${DOCKER_DATA}/nzbdav/.env
    volumes:
      - ${DOCKER_DATA}/nzbdav/config:/config
      - /mnt:/mnt:rshared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  nzbdav-rclone:
    image: rclone/rclone@sha256:8a17d9b5cd5ce71bbb42e49e92ee83575d7fb03f6233d949d328e9d029b9376d
    container_name: nzbdav-rclone
    hostname: nzbdav-rclone
    restart: unless-stopped
    networks:
      - proxy-network
    env_file:
      - ${DOCKER_DATA}/nzbdav/.env
    volumes:
      - ${DOCKER_DATA}/nzbdav/rclone.conf:/config/rclone/rclone.conf:ro
      - ${DOCKER_DATA}/nzbdav/entrypoint.sh:/entrypoint.sh
      - /mnt/.cache:/mnt/.cache:/root/.cache/rclone  
      - /mnt/nzbdav/data/:/data:rshared #data here comes from the entrypoint.sh where the webdav is mounted inside the container
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      nzbdav:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    stop_grace_period: 30s
    init: true

networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true
