#THIS file must exist in order for rclone to be able to connect to the nzb-dav container.
# Credentials must be filled out 
[nzb-dav]
type = webdav
url = http://nzbdav:3000
vendor = other
user = 
pass = 