services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns@sha256:19bd73d8aea9641dc329ec18ae693b2b9c33ff7cdc007f368266ce584446f995 #image: oznu/cloudflare-ddns:latest
    container_name: cloudflare
    hostname: cloudflare
    restart: always
    network_mode: 'host'    
    environment:
      API_KEY: ${encryption}
      PUID: ${PUID}
      PGID: ${PGID}
      PROXIED: ${PROXIED}
      SUBDOMAIN: ${SUBDOMAIN}
      ZONE: ${ZONE}
    labels:
      backrest.backup: "false"
      backrest.priority: "low"
      backrest.action: "none"