services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare
    hostname: cloudflare
    restart: always
    network_mode: 'host'    
    environment:
      API_KEY: ${encryption}
      PUID: ${PUID}
      PGID: ${PGID}
      PROXIED: ${PROXIED}
      SUBDOMAIN: ${SUBDOMAIN}
      ZONE: ${ZONE}