
services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.6.0 
    container_name: pocketid
    hostname: pocketid-local
    restart: unless-stopped
    ports:
      - 1411:1411
    networks:
      - proxy-network
    env_file: 
      - .env
    volumes:
      - ${DOCKER_DATA}/pocketid/data:/app/data
    # Optional healthcheck.
    healthcheck:
      test: ["CMD", "/app/pocket-id", "healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    labels:
      backrest.backup: "true"
      backrest.priority: "critical"
      backrest.action: "stop"
      backrest.wait-time: "30"

networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true
