services:
  bentopdf:
    image: bentopdfteam/bentopdf:v2.3.3
    container_name: bentopdf
    hostname: bentopdf
    restart: unless-stopped
    ports:
      - '8087:8080'
    networks:
      - myNetwork
    
networks:
  myNetwork:
    external: true