services:
  # --- BASE TEMPLATE (never runs directly) ---
  backrest-base:
    image: garethgeorge/backrest:v1.12.1
    profiles:
      - donotrun
    restart: unless-stopped
    ports:
      - 9898:9898
    networks:
      - proxy-network
    environment:
      BACKREST_DATA: /data # path for backrest data. restic binary and the database are placed here.
      BACKREST_CONFIG: /config/config.json # path for the backrest config file.
      XDG_CACHE_HOME: /cache # path for the restic cache which greatly improves performance.
      TZ: ${TZ} # set the timezone for the container, used as the timezone for cron jobs.
    volumes:
      - ${DOCKER_DATA}:/mydocker
      - ${DOCKER_PATH}/backrest/data:/data
      - ${DOCKER_PATH}/backrest/config:/config
      - ${DOCKER_PATH}/backrest/cache:/cache
      - ${DOCKER_PATH}/backrest/tmp:/tmp
      - ${DOCKER_PATH}/backrest/logs:/var/log/backrest
      - ${SCRIPTS_PATH}:/usr/local/bin/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock
      #- ${DOCKER_DATA}/backrest/rclone:/root/.config/rclone # Mount for rclone config (needed when using rclone remotes)
      #- /MY-BACKUP-DATA:/userdata # [optional] mount local paths to backup here.
      #- /MY-REPOS:/repos # [optional] mount repos if using local storage, not necessary for remotes e.g. B2, S3, etc.

  # --- 1. STANDARD PROFILE ---
  backrest:
    extends:
      service: backrest-base
    container_name: backrest
    profiles:
      - standard

  # --- 2. PRIVATE BACKUP ---
  backrest-private:
    extends:
      service: backrest-base
    container_name: backrest-private
    hostname: backrest-${INSTANCE_NAME}
    profiles:
      - private
    volumes:
      # adds private backup source + repo storage
      - ${PRIVATE_DATA:-/tmp}:${PRIVATE_DATA:-/tmp}:ro
    
networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true
