services:
  newt:
    image: fosrl/newt:1.10.4
    container_name: newt
    hostname: pangolin-agent
    restart: unless-stopped
    networks:
      - pangolin-network
    env_file: 
      - .env
    environment:
      PANGOLIN_ENDPOINT: ${PANGOLIN_ENDPOINT}
      NEWT_ID: ${NEWT_ID}
      NEWT_SECRET: ${NEWT_SECRET}

networks:
  pangolin-network:
    name: pangolin-network
    external: true