services:
  app:
    image: ghcr.io/sooti/stremio-addon-debrid-search:v1.9.1
    container_name: sootio
    hostname: sootio
    restart: unless-stopped
    ports:
      - ${PORT:-6907}:${PORT:-6907}
    networks:
      - proxy-network
    env_file:
      - ${DOCKER_DATA}/sootio/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ${DOCKER_DATA}/sootio/data:/app/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
        reservations:
          cpus: "0.1"
    labels:
      backrest.backup: "true"
      backrest.priority: "high"
      backrest.action: "stop"
      backrest.wait-time: "30"
    
networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true
