x-backrest-labels: &backrest-labels
    backrest.backup: "true"
    backrest.priority: "high"
    backrest.action: "stop"
services:
  databasus:
    image: databasus/databasus:v3.33.0
    container_name: db-backups
    hostname: databasus
    restart: unless-stopped
    ports:
      - 4005:4005
    networks:
      - proxy-network
      - db-network
    volumes:
      - /mnt/docker/db-backups:/databasus-data
    labels:
      <<: *backrest-labels
      backrest.wait-time: "30"
        
networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true
  db-network:
    name: db-net
    external: true  