services:
  databasus:
    image: databasus/databasus:v3.21.0
    container_name: db-backups
    hostname: databasus
    restart: unless-stopped
    ports:
      - "4005:4005"
    networks:
      - proxy-network
      - db-network
    volumes:
      - /mnt/docker/db-backups:/databasus-data
        
networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true
  db-network:
    name: db-net
    external: true  