x-labels-backrest: &labels-backrest
  backrest.backup: "true"
  backrest.priority: "medium"
  backrest.action: "none"

name: pangolin
services:             #[Versions: 1.15.4 and 1.13.1 worked best on the VPS]
  pangolin:
    image: fosrl/pangolin:1.17.0
    container_name: pangolin
    hostname: pangolin-vps
    restart: unless-stopped
    environment:
      NODE_OPTIONS: --max-old-space-size=600
      DASHBOARD_URL: ${DASHBOARD_URL}
      BASE_DOMAIN: ${BASE_DOMAIN}
      SERVER_SECRET: ${SERVER_SECRET}
    env_file:
      - ${DOCKER_DATA}/pangolin/config/.env
    volumes:
      - ${DOCKER_DATA}/pangolin/config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "10s" 
      timeout: "10s"   
      retries: 15
    labels:
      <<: *labels-backrest

#    mem_limit: 700m
#    memswap_limit: 1g

  gerbil:
    image: fosrl/gerbil:1.3.1
    container_name: gerbil
    hostname: gerbil-vps
    restart: unless-stopped
    ports:
      - 51821:51821/udp
      - 21820:21820/udp
      - 443:443
      - 80:80
    environment:
      TZ: ${TZ}
    depends_on:
      pangolin:
        condition: service_healthy
    command:
#      - /wait-for-pangolin.sh
 #     - gerbil
      - --reachableAt=http://gerbil:3004
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/
    volumes:
      - ${DOCKER_DATA}/pangolin/config/:/var/config
      #- ${DOCKER_DATA}/pangolin/wait-for-pangolin.sh:/wait-for-pangolin.sh:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    labels:
      <<: *labels-backrest
    
#    mem_limit: 80m
#    memswap_limit: 160m

  traefik:
    image: traefik:v3.6.13
    container_name: traefik
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      BASE_DOMAIN: ${BASE_DOMAIN}
      DASHBOARD_URL: ${DASHBOARD_URL}
      EMAIL: ${EMAIL}
    network_mode: service:gerbil
    depends_on:
      pangolin:
        condition: service_healthy
    entrypoint: sh -c "apk add --no-cache gettext && /scripts/start-traefik.sh"
    volumes:
      - ${DOCKER_DATA}/pangolin/scripts:/scripts:ro
      - ${DOCKER_DATA}/pangolin/config/traefik:/etc/traefik
      - ${DOCKER_DATA}/pangolin/config/letsencrypt:/letsencrypt
      - ${DOCKER_DATA}/pangolin/config/traefik/logs:/var/log/traefik
    labels:
      <<: *labels-backrest    
#     mem_limit: 100m
#     memswap_limit: 200m

    crowdsec:
      image: docker.io/crowdsecurity/crowdsec:v1.7.7
      container_name: crowdsec
      hostname: crowdsec-vps
      restart: unless-stopped
      ports:
        - 6060:6060 # Metrics endpoint
        - 8080:8080 # Local API port (needed if you add host firewall later)
      environment:
      #  GID: "1000"
        TZ: ${TZ}
        COLLECTIONS: crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
        ENROLL_INSTANCE_NAME: "pangolin-crowdsec"
        PARSERS: crowdsecurity/whitelists
        ENROLL_TAGS: docker
        BOUNCER_KEY_TRAEFIK: ${CROWDSEC_API_KEY}
      healthcheck:
        test: ["CMD", "cscli", "lapi", "status"]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 30s
      labels:
        - "traefik.enable=false"
        <<: *labels-backrest
      volumes:
        # Crowdsec config and data (Updated to be inside pangolin)
        - ${DOCKER_DATA}/pangolin/config/crowdsec/config:/etc/crowdsec
        - ${DOCKER_DATA}/pangolin/config/crowdsec/data:/var/lib/crowdsec/data
        # Read Traefik logs (unchanged)
        - ${DOCKER_DATA}/pangolin/config/traefik/logs:/var/log/traefik:ro
      
networks:
  default:
    driver: bridge
    name: pangolin-net
    external: true
      