services:
  bentopdf:
    image: bentopdfteam/bentopdf:2.8.2
    container_name: bentopdf
    hostname: bentopdf
    restart: unless-stopped
    ports:
      - 8087:8080
    networks:
      - proxy-network
    
networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true