services:
  bentopdf:
    image: bentopdfteam/bentopdf:2.8.4
    container_name: bentopdf
    hostname: bentopdf
    restart: unless-stopped
    ports:
      - 8087:8080
    networks:
      - proxy-network
    labels:
      backrest.backup: "true"
      backrest.priority: "low"
      backrest.action: "none"
    
    
networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true