x-labels-backrest: &labels-backrest  
  backrest.backup: "true"
  backrest.priority: "high"
  backrest.action: "stop"
  backrest.wait-time: "30"

services:
  aiometadata:
    image: ghcr.io/cedya77/aiometadata@sha256:8dc101e8109810fa9d364e67f9d40299b6c239285140234ef2a81e2c40646512
    container_name: aiometadata
    hostname: aiometadata
    restart: unless-stopped
    env_file:
      - ${DOCKER_DATA}/aiometadata/.env
    ports:
      - 3232:3232
    networks:
      - proxy-network
    volumes:
      - ${DOCKER_DATA}/aiometadata/data:/app/addon/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3232/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      aiometadata_redis:
        condition: service_healthy
    labels:
      <<: *labels-backrest

  aiometadata_redis:
    image: redis:8.6.1
    container_name: aiometadata_redis
    restart: unless-stopped
    networks:
      - proxy-network
    volumes:
      - ${DOCKER_DATA}/aiometadata/redis-cache:/data
    command: redis-server --appendonly yes --save 60 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      <<: *labels-backrest

networks:  
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true