services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.33.1
    container_name: zerobyte
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - 4096:4096
    networks:
      - proxy-network
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      TZ: ${TZ}
      BASE_URL: ${BASE_URL:-http://localhost:4096} 
      APP_SECRET: ${APP_SECRET} # generate one with `openssl rand -hex 32`
      TRUSTED_ORIGINS: ${TRUSTED_ORIGINS} # Comma-separated list of trusted origins for CORS
      TRUST_PROXY: ${TRUST_PROXY} 
      RESTIC_HOSTNAME: ${RESTIC_HOSTNAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA}/zerobyte:/var/lib/zerobyte
      - ${DOCKER_DATA}:/data
networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true