x-labels-backrest: &labels-backrest
  backrest.backup: "true"
  backrest.priority: "low"
  backrest.action: "none"

services:
  epg-grabber:
    image: ghcr.io/iptv-org/epg:master
    container_name: epg-grabber
    hostname: epg-grabber
    restart: unless-stopped
    ports:
      - 3300:3000
    networks:
      - proxy-network
    environment:
      CRON_SCHEDULE: 0 4 * * *
      DAYS: 2
      MAX_CONNECTIONS: 1
      DELAY: 15000
      GZIP: "true"
      RUN_AT_STARTUP: "true"
      TZ: ${TZ}
    volumes:
      - ${DOCKER_DATA}/iptv-org/epg-grabber/channels.xml:/epg/public/channels.xml
      - ${DOCKER_DATA}/iptv-org/epg-grabber/sites/tv.nu:/epg/sites/tv.nu/
    labels:
      <<: *labels-backrest

networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true