#########################################################################
### CURRENTLY IN USE ON FOLLOWING SERVERS: RMC-1, RMC-2, DIETPI, STREMIO
######################################################################### 
services:
  newt:
    image: fosrl/newt:1.10.4
    container_name: pangolin-newt
    hostname: ${NEWT_HOSTNAME}
    restart: unless-stopped
    networks:
      - pangolin-network
    env_file: 
      - .env

networks:
  pangolin-network:
    name: pangolin-net
    external: true