#########################################################################
### CURRENTLY IN USE ON FOLLOWING SERVERS: RMC-1, RMC-2, DIETPI, STREMIO
######################################################################### 
services:
  newt:
    image: fosrl/newt:1.12.2
    container_name: pangolin-newt
    hostname: ${NEWT_HOSTNAME}
    restart: unless-stopped
    networks:
      - pangolin-network
    env_file: 
      - .env
    labels:
      backrest.backup: "true"
      backrest.priority: "low"
      backrest.action: "none"

networks:
  pangolin-network:
    name: pangolin-net
    external: true