services:
  databasus:
    image: databasus/databasus:v2.20.3
    container_name: db-backups
    hostname: databasus
    restart: unless-stopped
    ports:
      - "4005:4005"
    networks:
      - myNetwork
    volumes:
      - /mnt/docker/db-backups:/databasus-data
    
networks:
  myNetwork:
    external: true