services:
  # --- BASE TEMPLATE (Will never run on its own) ---
  zerobyte-base:
    image: ghcr.io/nicotsx/zerobyte:v0.33.1
    profiles:
      - donotrun
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - 4096:4096
    networks:
      - proxy-network
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      TZ: ${TZ}
      BASE_URL: ${BASE_URL:-http://localhost:4096}
      APP_SECRET: ${APP_SECRET}
      TRUSTED_ORIGINS: ${TRUSTED_ORIGINS}
      TRUST_PROXY: ${TRUST_PROXY}
      RESTIC_HOSTNAME: ${RESTIC_HOSTNAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_PATH}/zerobyte:/var/lib/zerobyte
      - ${DOCKER_DATA}:/data

  # --- 1. STANDARD DEPLOYMENT ---
  zerobyte:
    extends:
      service: zerobyte-base
    container_name: zerobyte
    profiles:
      - standard

  # --- 2. PRIVATE DEPLOYMENT ---
  zerobyte-private:
    extends:
      service: zerobyte-base
    container_name: zerobyte-private
    profiles:
      - private
    volumes:
      # This safely appends to the 3 volumes inherited from the base
      - ${PRIVATE_DATA:-/tmp}:${PRIVATE_DATA:-/tmp}:ro
  zerobyte-nfs:
    extends:
      service: zerobyte-base
    container_name: zerobyte-nfs
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    profiles:
      - nfs
    volumes:
      # This safely appends to the 3 volumes inherited from the base
      - ${NFS_DATA:-/tmp}:${NFS_DATA:-/tmp}

networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true