x-aiostreams-base: &aiostreams-base
  restart: unless-stopped
  networks:
    - proxy-network
  environment:
    TZ: ${TZ}
  env_file:
    - .env
  healthcheck:
    test: wget -qO- http://localhost:3000/api/v1/status
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 10s
  labels:
    backrest.backup: "true"
    backrest.priority: "medium"
    backrest.action: "none"
    
services:
  aiostreams:
    <<: *aiostreams-base
    image: ghcr.io/viren070/aiostreams:2026.05.02.2017-nightly
    container_name: aiostreams-nightly
    hostname: aiostreams-nightly
    ports:
      - 3001:3000
    volumes:
      - ${DOCKER_DATA}/aiostreams-nightly/data:/app/data

networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true