## CURENTLY IN USE in DOCKER ON VPS and MEDIA ##
## AS BINARY IN NETBIRD LXC, RMC-1, RMC-2 and WIZ ### 
services:
  netbird:
    image: netbirdio/netbird:0.68.1
    container_name: netbird-client
    hostname: netbird-${NETBIRD_HOSTNAME}
    restart: always
    network_mode: host
    devices:
      # Required when using userspace mode or when kernel module is not available
      - /dev/net/tun
    env_file:
      -  ${DOCKER_PATH}/netbird/.env
    environment:
      NB_LOG_LEVEL: info
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    volumes:
      - ${DOCKER_PATH}/netbird/:/var/lib/netbird
    
    #privileged: true
    #mem_limit: 80m
    #memswap_limit: 160m
    