services:
  hbbs:
    image: rustdesk/rustdesk-server:1.1.15
    container_name: rustdesk-hbbs
    restart: unless-stopped
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    networks:
      - myNetwork
    command: hbbs -r ${ENDPOINT}:21117
    volumes:
      - ${DOCKER_DATA}/rustdesk/data:/root
    depends_on:
      - hbbr
    
  hbbr:
    image: rustdesk/rustdesk-server:1.1.15
    container_name: rustdesk-hbbr
    restart: unless-stopped
    ports:
      - 21117:21117
      - 21119:21119
    networks:
      - myNetwork
    command: hbbr
    volumes:
      - ${DOCKER_DATA}/rustdesk/data:/root

networks:
  myNetwork:
    external: true