services:
  fastapi-dls:
    image: collinwebdesigns/fastapi-dls:2.0.3
    container_name: fastapi-dls
    hostname: fastapi-dls
    restart: always
    networks:
      - proxy-network
    ports:
      - 443:443
    environment:
      TZ: ${TZ}
      DLS_URL: ${DLS_URL:-192.168.10.90}
      DLS_PORT: 443
      LEASE_EXPIRE_DAYS: 90
    volumes:
      - ${DOCKER_DATA}/fastapi-dls/cert:/app/cert
      - nvidia-license-db:/app/database
    labels:
      backrest.backup: "true"
      backrest.priority: "low"
      backrest.action: "none"

volumes:
  nvidia-license-db:
    name: "nvidia-license-db"

networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true