x-aiostreams-base: &aiostreams-base
  restart: unless-stopped
  networks:
    - proxy-network
  environment:
    TZ: ${TZ}
  env_file:
    - ${DOCKER_DATA}/aiostreams/.env
  healthcheck:
    test: wget -qO- http://localhost:3000/api/v1/status
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 10s
    
services:
  aiostreams:
    <<: *aiostreams-base
    image: ghcr.io/viren070/aiostreams:v2.25.4
    container_name: aiostreams
    hostname: aiostreams-stable
    ports:
      - 3000:3000
    volumes:
      - ${DOCKER_DATA}/aiostreams/data:/app/data

networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true
