services:
  tautulli:
    image: tautulli/tautulli:v2.16.1
    container_name: tautulli
    hostname: tautulli
    restart: unless-stopped
    ports:
      - 7171:8181
    networks:
      - proxy-network
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      TEST_VAR: 'dummy_value_test'
    volumes:
      - ${DOCKER_DATA}/tautulli/config:/config

networks:  
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true