services:
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: guacd
    restart: unless-stopped
    networks:
      - internal-net
    
  postgres:
    image: postgres:15.17
    container_name: guac-db
    restart: unless-stopped
    ports:
      - 5434:5432
    networks:
      - internal-net
      - db-network
    env_file:
      - ${DOCKER_DATA}/apache/config/.env
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${GUACAMOLE_PSQL_PASS}
    volumes:
      - ${DOCKER_DATA}/apache/config/db:/var/lib/postgresql/data
      - ${DOCKER_DATA}/apache/config/guacamole/init:/docker-entrypoint-initdb.d
      
  guacamole:
    image: guacamole/guacamole:1.5.5
    container_name: guacamole
    restart: unless-stopped
    ports:
      - 8282:8080
    networks:
      - internal-net
      - proxy-network
    env_file:
      - ${DOCKER_DATA}/apache/config/.env
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: ${POSTGRESQL_DB}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${GUACAMOLE_PSQL_PASS}
      #GUACAMOLE_AUTH_PROVIDER: "openid"
      #OPENID_AUTHORIZATION_ENDPOINT: ${OPENID_AUTHORIZATION_ENDPOINT} 
      #OPENID_JWKS_ENDPOINT: ${OPENID_JWKS_ENDPOINT}
      #OPENID_TOKEN_ENDPOINT: ${OPENID_TOKEN_ENDPOINT}
      #OPENID_ISSUER: ${OPENID_ISSUER}
      #OPENID_USERINFO_ENDPOINT: ${OPENID_USERINFO_ENDPOINT}
      #OPENID_CLIENT_ID: ${OPENID_CLIENT_ID}
      #OPENID_CLIENT_SECRET: ${OPENID_CLIENT_SECRET}
      #OPENID_REDIRECT_URI: ${OPENID_REDIRECT_URI}
      #OPENID_SCOPE: "openid profile email"
      #OPENID_USERNAME_CLAIM_TYPE: "preferred_username"
    volumes:
      - ${DOCKER_DATA}/apache/config/guac:/guac-home
    depends_on:
      - guacd
      - postgres

networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true
  internal-net:
    driver: bridge
  db-network:
    name: db-net
    external: true
