services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.11.0
    container_name: mealie
    hostname: mealie
    restart: unless-stopped
    ports:
      - 9925:9000 
    networks:
      - proxy-network
    deploy:
      resources:
        limits:
          memory: 1000M # 
    environment:
      BASE_URL: ${BASE_URL} #https://recept.stanikz.com
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      ALLOW_SIGNUP: true
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
    #Needs to be moved to a bind mount for persistence e.g: ${DOCKER_DATA}/services/mealie/data:/app/data/
    volumes:
      - mealie-data:/app/data/ 

volumes:
  mealie-data:
    driver: local    

networks:
  proxy-network:
    name: ${EXTERNAL_NETWORK_NAME:-proxy-network}
    external: true